version: "3.1"
services:
    nginx:
        image: nginx:alpine
        container_name: fp-nginx
        working_dir: /apps
        volumes:
            - ./apps:/apps
            - ./configs/nginx/local.conf:/etc/nginx/conf.d/default.conf
            - ./log/nginx:/var/log/nginx
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"

    php-fpm:
        build: configs/php-fpm
        container_name: fp-php-fpm
        working_dir: /apps
        volumes:
            - ./apps:/apps
            - ./configs/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    mysql:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
        container_name: fp-mysql
        working_dir: /apps
        volumes:
            - ./apps:/apps
            - ./data/mysql:/var/lib/mysql
            - ./log/mysql:/var/log/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"
